[package]
name = "iced_drop"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["examples/*"]

[workspace.dependencies.iced]
git = "https://github.com/nrjais/iced"
branch = "editor"
features = ["advanced"]

[dependencies]
iced.workspace = true
